service: uploader-js

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev

functions:
  hello:
    handler: handlers.hello
  register:
    handler: handlers.register
    events:
      - http:
          path: register
          method: post
